language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/coverage.xml

after_script:
  - ./vendor/bin/coveralls -v --coverage_clover build/logs/coverage.xml

notifications:
  email:
    - travis-github@nntoan.com
